### ISSUE TITLE
Build a Serving Module

### ISSUE THREAD

**Issue by kalebheitzman** [HeitzmanCo/ChristChurchRaleigh-Theme#3]
Checkout [sapres.org](http://sapres.org) under give back (replicate the ui, google map)

**Comment by kalebheitzman** [comment]
I have a link for spares.org. Obviously that isn't right...

**Comment by jeremytackett** [comment]
Once we have the framework for how this will work, let's do something similar with “grow” options.

i.e., let people select by age group, day of the week it meets, time, etc.?

My thought was that we could create one page type to use for serve opportunities and grow opportunities. So that the “look” of the page and where info is on the page gets really familiar.

**Comment by jeremytackett** [comment]
sapres.org

**Comment by kalebheitzman** [comment]
You can start entering serve opportunities under event page type
