### ISSUE TITLE
Tweaks for "serve" entries

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#77]
- [ ] ~~Need to be able to select multiple times of day and days of the week~~
- [x] On "When" under "Lunch Buddies at Hope Charter School" I want to say "Weekdays, morning or afternoon" but it keeps changing it back when I update the text. **Bug?**
- [x] Add "Family Friendly" as a search option.
- [x] Add optional fields for secondary contact (name, phone, email) under the "Contact Information" section
- [x] On individual serve page, don't show fields that are blank (i.e., Phone under Wake Relief contact) https://ccral.org/serve/wake-relief-shift-volunteer
- [x] Under "Where" on the back-end serve area, replace with Location and Address (two fields)
- [x] There's a broken image link showing up under the "more opportunities" button on individual pages. 
  <img width="1136" alt="screen shot 2016-10-13 at 1 03 30 pm" src="https://cloud.githubusercontent.com/assets/22300799/19358832/79eefbbe-9145-11e6-9f3e-cab80098e488.png">

**Comment by kalebheitzman** [comment]
Hey you get your first won't fix unless you just really need this. Selecting multiple times of day/days of week is super complicated. I'd have to change quite a bit of code to get that working (Assuming I can) and it would clutter up your UI (makes it look more like a backend form instead of a simple front-end dropdown).

**Comment by kalebheitzman** [comment]
Everything but selecting multiple items (troublesome code rewrite) are completed.
